import Header from '../../components/Header'
import Footer from '../../components/Footer'
import SEO from '../../components/SEO'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

export default function FAQ() {
  const faqItems = [
    {
      question: "What is an SSN?",
      answer: "SSN stands for Social Security Number. It's a unique nine-digit number issued by the U.S. Social Security Administration to U.S. citizens, permanent residents, and temporary working residents."
    },
    {
      question: "Are the generated SSNs real?",
      answer: "No, the SSNs generated by this tool are not real. They are random numbers formatted to look like SSNs for educational and testing purposes only."
    },
    {
      question: "Can I use these generated SSNs for official purposes?",
      answer: "Absolutely not. Using fake SSNs for official purposes is illegal. This tool is for educational and testing purposes only."
    },
    {
      question: "How does the SSN generator work?",
      answer: "The generator creates random numbers that follow the SSN format (XXX-XX-XXXX) and structure. It takes into account historical state-based assignments, year of issuance, and avoids known invalid combinations."
    },
    {
      question: "What are invalid SSN combinations?",
      answer: "Invalid SSN combinations include area numbers 000, 666, or 900-999, group number 00, and serial number 0000. Our generator excludes these by default."
    },
    {
      question: "How accurate is the state-based SSN generation?",
      answer: "Our state-based generation uses historical area number ranges assigned to each state. However, please note that since 2011, SSNs are no longer assigned based on state, so this feature is mainly for educational purposes about historical SSN assignment practices."
    },
    {
      question: "What changed in SSN assignment in 2011?",
      answer: "In June 2011, the Social Security Administration began assigning SSNs randomly, rather than based on geographic region. This change was made to extend the longevity of the nine-digit SSN nationwide."
    },
    {
      question: "Is it safe to use this SSN generator?",
      answer: "Yes, it's safe to use for educational and testing purposes. However, always remember that these are not real SSNs and should not be used as such. Be cautious about where you enter or store the generated numbers."
    },
    {
      question: "Can the SSN validator determine if an SSN is currently in use?",
      answer: "No, our validator only checks if the SSN follows the correct format and structure. It cannot determine if an SSN is actually in use or assigned to someone."
    },
    {
      question: "Why do you offer bulk SSN generation?",
      answer: "Bulk SSN generation is useful for developers and testers who need to populate databases or test systems with multiple SSN-like numbers quickly. Remember, these should only be used in secure, non-production environments."
    }
  ]

  return (
    <>
      <SEO 
        title="Frequently Asked Questions about SSN Generator"
        description="Find answers to common questions about our SSN Generator tool, its usage, and Social Security Numbers in general."
      />
      <div className="min-h-screen flex flex-col bg-gradient-to-br from-indigo-100 to-purple-100">
        <Header />
        <main className="flex-grow container mx-auto px-4 py-8 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-indigo-700 mb-6 sm:text-4xl lg:text-5xl">Frequently Asked Questions</h2>
          <Accordion type="single" collapsible className="w-full bg-white rounded-lg shadow-md">
            {faqItems.map((item, index) => (
              <AccordionItem value={`item-${index}`} key={index}>
                <AccordionTrigger className="text-sm sm:text-base">{item.question}</AccordionTrigger>
                <AccordionContent className="text-sm sm:text-base">{item.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </main>
        <Footer />
      </div>
    </>
  )
}

